name: Deploy MkDocs
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install -U mkdocs pymdown-extensions mkdocs-terminal  # add other plugins/themes as needed
      - run: mkdocs build --strict
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site        # uploads your built site to gh-pages branch
          # action auto-creates a `.nojekyll` so Pages won’t try Jekyll

